<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="65" failures="0" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestValidateIpv4Address-20201011210403" skipped="0" tests="65" time="0.215" timestamp="2020-10-11T21:04:07">
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_empty_ipv4_address" time="0.007" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 15, in test_empty_ipv4_address
    is_valid = subnet_calculator.validate_ipv4_address('')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_at_255" time="0.004" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 115, in test_ipv4_with_all_octet_values_at_255
    is_valid = subnet_calculator.validate_ipv4_address('255.255.255.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_at_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 90, in test_ipv4_with_all_octet_values_at_zero
    is_valid = subnet_calculator.validate_ipv4_address('0.0.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_one_above_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 120, in test_ipv4_with_all_octet_values_one_above_255
    is_valid = subnet_calculator.validate_ipv4_address('256.256.256.256')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_one_above_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 95, in test_ipv4_with_all_octet_values_one_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('1.1.1.1')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_one_below_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 110, in test_ipv4_with_all_octet_values_one_below_255
    is_valid = subnet_calculator.validate_ipv4_address('254.254.254.254')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_one_below_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 85, in test_ipv4_with_all_octet_values_one_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('-1.-1.-1.-1')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_well_above_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 125, in test_ipv4_with_all_octet_values_well_above_255
    is_valid = subnet_calculator.validate_ipv4_address('999.999.999.999')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_well_above_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 100, in test_ipv4_with_all_octet_values_well_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('100.200.100.200')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_well_below_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 105, in test_ipv4_with_all_octet_values_well_below_255
    is_valid = subnet_calculator.validate_ipv4_address('50.50.50.50')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_all_octet_values_well_below_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 80, in test_ipv4_with_all_octet_values_well_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('-255.-255.-255.-255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_correct_following_zero_padding" time="0.002" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 331, in test_ipv4_with_correct_following_zero_padding
    is_valid = subnet_calculator.validate_ipv4_address('160.100.25.700')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_empty_octet" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 75, in test_ipv4_with_empty_octet
    is_valid = subnet_calculator.validate_ipv4_address('123..123.123')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_at_255" time="0.002" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 164, in test_ipv4_with_first_octet_value_at_255
    is_valid = subnet_calculator.validate_ipv4_address('255.0.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_at_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 139, in test_ipv4_with_first_octet_value_at_zero
    is_valid = subnet_calculator.validate_ipv4_address('0.10.10.10')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_one_above_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 169, in test_ipv4_with_first_octet_value_one_above_255
    is_valid = subnet_calculator.validate_ipv4_address('256.0.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_one_above_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 144, in test_ipv4_with_first_octet_value_one_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('1.0.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_one_below_255" time="0.005" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 159, in test_ipv4_with_first_octet_value_one_below_255
    is_valid = subnet_calculator.validate_ipv4_address('254.0.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_one_below_zero" time="0.004" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 135, in test_ipv4_with_first_octet_value_one_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('-1.1.1.1')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_well_above_255" time="0.005" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 174, in test_ipv4_with_first_octet_value_well_above_255
    is_valid = subnet_calculator.validate_ipv4_address('999.0.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_well_above_zero" time="0.005" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 149, in test_ipv4_with_first_octet_value_well_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('100.0.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_well_below_255" time="0.006" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 154, in test_ipv4_with_first_octet_value_well_below_255
    is_valid = subnet_calculator.validate_ipv4_address('50.255.255.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_first_octet_value_well_below_zero" time="0.008" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 130, in test_ipv4_with_first_octet_value_well_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('-255.5.5.5')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_four_octets_valid" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 60, in test_ipv4_with_four_octets_valid
    is_valid = subnet_calculator.validate_ipv4_address('123.123.123.123')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_at_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 311, in test_ipv4_with_fourth_octet_value_at_255
    is_valid = subnet_calculator.validate_ipv4_address('0.0.0.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_at_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 286, in test_ipv4_with_fourth_octet_value_at_zero
    is_valid = subnet_calculator.validate_ipv4_address('10.10.10.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_one_above_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 316, in test_ipv4_with_fourth_octet_value_one_above_255
    is_valid = subnet_calculator.validate_ipv4_address('0.0.0.256')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_one_above_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 291, in test_ipv4_with_fourth_octet_value_one_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('0.0.0.1')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_one_below_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 306, in test_ipv4_with_fourth_octet_value_one_below_255
    is_valid = subnet_calculator.validate_ipv4_address('0.0.0.254')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_one_below_zero" time="0.002" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 282, in test_ipv4_with_fourth_octet_value_one_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('1.1.1.-1')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_well_above_255" time="0.004" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 321, in test_ipv4_with_fourth_octet_value_well_above_255
    is_valid = subnet_calculator.validate_ipv4_address('0.0.0.999')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_well_above_zero" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 296, in test_ipv4_with_fourth_octet_value_well_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('0.0.0.50')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_well_below_255" time="0.002" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 301, in test_ipv4_with_fourth_octet_value_well_below_255
    is_valid = subnet_calculator.validate_ipv4_address('255.255.255.50')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_fourth_octet_value_well_below_zero" time="0.002" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 277, in test_ipv4_with_fourth_octet_value_well_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('5.5.5.-255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_incorrect_leading_zero_padding" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 326, in test_ipv4_with_incorrect_leading_zero_padding
    is_valid = subnet_calculator.validate_ipv4_address('160.010.25.007')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_no_digits_in_octet" time="0.005" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 20, in test_ipv4_with_no_digits_in_octet
    is_valid = subnet_calculator.validate_ipv4_address('....')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_octets_one_above_valid" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 65, in test_ipv4_with_octets_one_above_valid
    is_valid = subnet_calculator.validate_ipv4_address('123.123.123.123.123')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_octets_one_below_valid" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 55, in test_ipv4_with_octets_one_below_valid
    is_valid = subnet_calculator.validate_ipv4_address('123.123.123')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_octets_well_above_valid" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 70, in test_ipv4_with_octets_well_above_valid
    is_valid = subnet_calculator.validate_ipv4_address('123.123.123.123.123.123.123.123')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_one_less_than_three_digits_in_octet" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 30, in test_ipv4_with_one_less_than_three_digits_in_octet
    is_valid = subnet_calculator.validate_ipv4_address('11.11.11.11')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_one_more_than_three_digits_in_octet" time="0.004" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 40, in test_ipv4_with_one_more_than_three_digits_in_octet
    is_valid = subnet_calculator.validate_ipv4_address('1111.1111.1111.1111')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_one_octets_well_below_valid" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 50, in test_ipv4_with_one_octets_well_below_valid
    is_valid = subnet_calculator.validate_ipv4_address('123')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_at_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 213, in test_ipv4_with_second_octet_value_at_255
    is_valid = subnet_calculator.validate_ipv4_address('0.255.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_at_zero" time="0.002" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 188, in test_ipv4_with_second_octet_value_at_zero
    is_valid = subnet_calculator.validate_ipv4_address('10.0.10.10')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_one_above_255" time="0.003" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 218, in test_ipv4_with_second_octet_value_one_above_255
    is_valid = subnet_calculator.validate_ipv4_address('0.256.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_one_above_zero" time="0.002" timestamp="2020-10-11T21:04:06">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 193, in test_ipv4_with_second_octet_value_one_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('0.1.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_one_below_255" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 208, in test_ipv4_with_second_octet_value_one_below_255
    is_valid = subnet_calculator.validate_ipv4_address('0.254.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_one_below_zero" time="0.004" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 184, in test_ipv4_with_second_octet_value_one_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('1.-1.1.1')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_well_above_255" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 223, in test_ipv4_with_second_octet_value_well_above_255
    is_valid = subnet_calculator.validate_ipv4_address('0.999.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_well_above_zero" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 198, in test_ipv4_with_second_octet_value_well_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('0.50.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_well_below_255" time="0.004" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 203, in test_ipv4_with_second_octet_value_well_below_255
    is_valid = subnet_calculator.validate_ipv4_address('255.50.255.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_second_octet_value_well_below_zero" time="0.004" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 179, in test_ipv4_with_second_octet_value_well_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('5.-255.5.5')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_at_255" time="0.004" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 262, in test_ipv4_with_third_octet_value_at_255
    is_valid = subnet_calculator.validate_ipv4_address('0.0.255.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_at_zero" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 237, in test_ipv4_with_third_octet_value_at_zero
    is_valid = subnet_calculator.validate_ipv4_address('10.10.0.10')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_one_above_255" time="0.002" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 267, in test_ipv4_with_third_octet_value_one_above_255
    is_valid = subnet_calculator.validate_ipv4_address('0.0.256.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_one_above_zero" time="0.002" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 242, in test_ipv4_with_third_octet_value_one_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('0.0.1.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_one_below_255" time="0.002" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 257, in test_ipv4_with_third_octet_value_one_below_255
    is_valid = subnet_calculator.validate_ipv4_address('0.0.254.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_one_below_zero" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 233, in test_ipv4_with_third_octet_value_one_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('1.1.-1.1')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_well_above_255" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 272, in test_ipv4_with_third_octet_value_well_above_255
    is_valid = subnet_calculator.validate_ipv4_address('0.0.999.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_well_above_zero" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 247, in test_ipv4_with_third_octet_value_well_above_zero
    is_valid = subnet_calculator.validate_ipv4_address('0.0.50.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_well_below_255" time="0.002" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 252, in test_ipv4_with_third_octet_value_well_below_255
    is_valid = subnet_calculator.validate_ipv4_address('255.255.50.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_third_octet_value_well_below_zero" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 228, in test_ipv4_with_third_octet_value_well_below_zero
    is_valid = subnet_calculator.validate_ipv4_address('5.5.-255.5')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_three_digits_in_octet" time="0.005" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 35, in test_ipv4_with_three_digits_in_octet
    is_valid = subnet_calculator.validate_ipv4_address('111.111.111.111')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_well_less_than_three_digits_in_octet" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 25, in test_ipv4_with_well_less_than_three_digits_in_octet
    is_valid = subnet_calculator.validate_ipv4_address('1.1.1.1')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateIpv4Address" name="test_ipv4_with_well_more_than_three_digits_in_octet" time="0.003" timestamp="2020-10-11T21:04:07">
		<error message="bad operand type for unary +: 'str'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 45, in test_ipv4_with_well_more_than_three_digits_in_octet
    is_valid = subnet_calculator.validate_ipv4_address('123456.123456.123456.123456')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 26, in validate_ipv4_address
    + r"|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]"
TypeError: bad operand type for unary +: 'str'
]]>		</error>
	</testcase>
</testsuite>
