<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="26" failures="0" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat-20201010091746" skipped="0" tests="26" time="0.057" timestamp="2020-10-10T09:17:47">
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_empty_netmask" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 429, in test_empty_netmask
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_maximum_bit_netmask_ending_in_254" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 514, in test_maximum_bit_netmask_ending_in_254
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.254')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_empty_octet" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 464, in test_netmask_with_empty_octet
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255..0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_many_non_zeros_after_one_zero" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 474, in test_netmask_with_many_non_zeros_after_one_zero
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('0.255.255.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_no_digits_in_octet" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 434, in test_netmask_with_no_digits_in_octet
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('....')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_non_valid_octet_value" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 554, in test_netmask_with_non_valid_octet_value
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.180')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_octet_less_than_255_before_255" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 484, in test_netmask_with_octet_less_than_255_before_255
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('0.255.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_octets_all_255" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 494, in test_netmask_with_octets_all_255
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_octets_all_zero" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 489, in test_netmask_with_octets_all_zero
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('0.0.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_octets_at_four" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 449, in test_netmask_with_octets_at_four
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_octets_one_above_four" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 454, in test_netmask_with_octets_one_above_four
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_octets_one_below_four" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 444, in test_netmask_with_octets_one_below_four
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_octets_well_above_four" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 459, in test_netmask_with_octets_well_above_four
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.255.255.255.255.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_octets_well_below_four" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 439, in test_netmask_with_octets_well_below_four
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_more_than_one_non_255_or_0_number" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 504, in test_netmask_with_one_more_than_one_non_255_or_0_number
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.248.240.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_non_255_or_0_number" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 499, in test_netmask_with_one_non_255_or_0_number
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.248.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_non_zero_after_many_non_zeros" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 479, in test_netmask_with_one_non_zero_after_many_non_zeros
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('0.0.0.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_non_zero_after_one_zero" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 469, in test_netmask_with_one_non_zero_after_one_zero
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('0.255.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_octet_with_valid_value_of_128" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 549, in test_netmask_with_one_octet_with_valid_value_of_128
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.128')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_octet_with_valid_value_of_192" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 544, in test_netmask_with_one_octet_with_valid_value_of_192
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.192')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_octet_with_valid_value_of_224" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 539, in test_netmask_with_one_octet_with_valid_value_of_224
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.224')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_octet_with_valid_value_of_240" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 534, in test_netmask_with_one_octet_with_valid_value_of_240
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.240')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_octet_with_valid_value_of_248" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 529, in test_netmask_with_one_octet_with_valid_value_of_248
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.248')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_octet_with_valid_value_of_252" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 524, in test_netmask_with_one_octet_with_valid_value_of_252
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.252')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_one_octet_with_valid_value_of_254" time="0.002" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 519, in test_netmask_with_one_octet_with_valid_value_of_254
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('255.255.255.254')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestIpv4ValidateNetmaskIpFormat" name="test_netmask_with_well_more_than_one_non_255_or_0_number" time="0.003" timestamp="2020-10-10T09:17:47">
		<error message="name 'NETMASK_MAX_PERIODS' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 509, in test_netmask_with_well_more_than_one_non_255_or_0_number
    is_valid = subnet_calculator.validate_ipv4_netmask_ip_format('254.248.240.128')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 52, in validate_ipv4_netmask_ip_format
    if (netmask.count('.') != NETMASK_MAX_PERIODS):
NameError: name 'NETMASK_MAX_PERIODS' is not defined
]]>		</error>
	</testcase>
</testsuite>
