<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestCalculateIpv6Address-20201010114523" skipped="0" tests="1" time="0.004" timestamp="2020-10-10T11:45:24">
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_minimum_ip_and_minimum_subnet" time="0.004" timestamp="2020-10-10T11:45:24">
		<failure message="'0.0.0.0' != '0:0:0:0:0:0:0:0'
- 0.0.0.0
+ 0:0:0:0:0:0:0:0
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 902, in test_calculate_subnet_in_bit_format_with_minimum_ip_and_minimum_subnet
    self.assertEquals('0.0.0.0', subnet)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '0.0.0.0' != '0:0:0:0:0:0:0:0'
- 0.0.0.0
+ 0:0:0:0:0:0:0:0

]]>		</failure>
	</testcase>
</testsuite>
