<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestConvertNetmaskBitsToBinary-20201008164813" skipped="0" tests="7" time="0.010" timestamp="2020-10-08T16:48:14">
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_maximum_netmask" time="0.001" timestamp="2020-10-08T16:48:13"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_minimum_netmask" time="0.001" timestamp="2020-10-08T16:48:13"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_netmask_one_above_minimum" time="0.001" timestamp="2020-10-08T16:48:13"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_netmask_one_below_maximum" time="0.001" timestamp="2020-10-08T16:48:13"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_netmask_well_above_minimum" time="0.001" timestamp="2020-10-08T16:48:14"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_netmask_well_below_maximum" time="0.001" timestamp="2020-10-08T16:48:14"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="testx" time="0.004" timestamp="2020-10-08T16:48:14">
		<failure message="'' != '00000000.00000000.00000000.00000000'
+ 00000000.00000000.00000000.00000000" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 655, in testx
    self.assertEquals('', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '' != '00000000.00000000.00000000.00000000'
+ 00000000.00000000.00000000.00000000
]]>		</failure>
	</testcase>
</testsuite>
