<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="subnet_calculator_tests.py" name="subnet_calculator_tests.CalculateUpperIpv6Range-20201011092008" skipped="0" tests="1" time="0.008" timestamp="2020-10-11T09:20:08">
	<testcase classname="subnet_calculator_tests.CalculateUpperIpv6Range" name="test_calculate_upper_range_at_minimum_ip_and_minimum_subnet" time="0.008" timestamp="2020-10-11T09:20:08">
		<failure message="'7fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff' != '7fff.ffff.ffff.ffff.ffff.ffff.ffff.ffff'
- 7fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
?     ^    ^    ^    ^    ^    ^    ^
+ 7fff.ffff.ffff.ffff.ffff.ffff.ffff.ffff
?     ^    ^    ^    ^    ^    ^    ^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 1154, in test_calculate_upper_range_at_minimum_ip_and_minimum_subnet
    self.assertEquals('7fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff', subnet)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '7fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff' != '7fff.ffff.ffff.ffff.ffff.ffff.ffff.ffff'
- 7fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
?     ^    ^    ^    ^    ^    ^    ^
+ 7fff.ffff.ffff.ffff.ffff.ffff.ffff.ffff
?     ^    ^    ^    ^    ^    ^    ^

]]>		</failure>
	</testcase>
</testsuite>
