{
  "errors": [],
  "failures": [
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_maximum_ip_and_well_below_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1127, in test_calculate_range_in_bit_format_maximum_ip_and_well_below_maximum_subnet\n    self.assertEquals('255.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '255.255.255.254' != '255.255.255.255'\n- 255.255.255.254\n?               ^\n+ 255.255.255.255\n?               ^\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_maximum_ip_and_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1117, in test_calculate_range_in_bit_format_with_maximum_ip_and_maximum_subnet\n    self.assertEquals('none', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: 'none' != '255.255.255.255'\n- none\n+ 255.255.255.255\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_maximum_ip_and_one_below_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1122, in test_calculate_range_in_bit_format_with_maximum_ip_and_one_below_maximum_subnet\n    self.assertEquals('255.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '255.255.255.254' != '255.255.255.255'\n- 255.255.255.254\n?               ^\n+ 255.255.255.255\n?               ^\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_minimum_ip_and_well_above_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1092, in test_calculate_range_in_bit_format_with_minimum_ip_and_well_above_minimum_subnet\n    self.assertEquals('0.15.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '0.15.255.254' != '5666104.5667215.255.255'\n- 0.15.255.254\n+ 5666104.5667215.255.255\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_one_above_minimum_ip_and_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1097, in test_calculate_range_in_bit_format_with_one_above_minimum_ip_and_minimum_subnet\n    self.assertEquals('127.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '127.255.255.254' != '1.1.1.1'\n- 127.255.255.254\n+ 1.1.1.1\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_one_above_minimum_ip_and_one_above_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1107, in test_calculate_range_in_bit_format_with_one_above_minimum_ip_and_one_above_minimum_subnet\n    self.assertEquals('63.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '63.255.255.254' != '1.1.1.1'\n- 63.255.255.254\n+ 1.1.1.1\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_one_below_maximum_ip_and_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1132, in test_calculate_range_in_bit_format_with_one_below_maximum_ip_and_maximum_subnet\n    self.assertEquals('none', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: 'none' != '254.254.254.254'\n- none\n+ 254.254.254.254\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_well_above_minimum_ip_and_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1102, in test_calculate_range_in_bit_format_with_well_above_minimum_ip_and_minimum_subnet\n    self.assertEquals('255.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '255.255.255.254' != '160.160.160.160'\n- 255.255.255.254\n+ 160.160.160.160\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_well_above_minimum_ip_and_well_above_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1112, in test_calculate_range_in_bit_format_with_well_above_minimum_ip_and_well_above_minimum_subnet\n    self.assertEquals('160.175.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '160.175.255.254' != '160.160.160.160'\n- 160.175.255.254\n+ 160.160.160.160\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_well_below_maximum_ip_and_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1137, in test_calculate_range_in_bit_format_with_well_below_maximum_ip_and_maximum_subnet\n    self.assertEquals('none', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: 'none' != '160.160.160.160'\n- none\n+ 160.160.160.160\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_bit_format_with_well_below_maximum_ip_and_well_below_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1147, in test_calculate_range_in_bit_format_with_well_below_maximum_ip_and_well_below_maximum_subnet\n    self.assertEquals('160.160.175.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '160.160.175.254' != '160.160.160.160'\n- 160.160.175.254\n+ 160.160.160.160\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_maximum_ip_and_well_below_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1067, in test_calculate_range_in_ip_format_maximum_ip_and_well_below_maximum_subnet\n    self.assertEquals('255.255.240.0', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '255.255.240.0' != '255.255.255.255'\n- 255.255.240.0\n+ 255.255.255.255\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_maximum_ip_and_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1057, in test_calculate_range_in_ip_format_with_maximum_ip_and_maximum_subnet\n    self.assertEquals('none', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: 'none' != '255.255.255.255'\n- none\n+ 255.255.255.255\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_maximum_ip_and_one_below_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1062, in test_calculate_range_in_ip_format_with_maximum_ip_and_one_below_maximum_subnet\n    self.assertEquals('255.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '255.255.255.254' != '255.255.255.255'\n- 255.255.255.254\n?               ^\n+ 255.255.255.255\n?               ^\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_minimum_ip_and_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1027, in test_calculate_range_in_ip_format_with_minimum_ip_and_minimum_subnet\n    self.assertEquals('127.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '127.255.255.254' != '127.255.255.255'\n- 127.255.255.254\n?               ^\n+ 127.255.255.255\n?               ^\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_minimum_ip_and_one_above_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1032, in test_calculate_range_in_ip_format_with_minimum_ip_and_one_above_minimum_subnet\n    self.assertEquals('63.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '63.255.255.254' != '63.255.255.255'\n- 63.255.255.254\n?              ^\n+ 63.255.255.255\n?              ^\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_minimum_ip_and_well_above_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1037, in test_calculate_range_in_ip_format_with_minimum_ip_and_well_above_minimum_subnet\n    self.assertEquals('0.15.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '0.15.255.254' != '0.15.255.255'\n- 0.15.255.254\n?            ^\n+ 0.15.255.255\n?            ^\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_one_above_minimum_ip_and_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1042, in test_calculate_range_in_ip_format_with_one_above_minimum_ip_and_minimum_subnet\n    self.assertEquals('127.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '127.255.255.254' != '1.1.1.1'\n- 127.255.255.254\n+ 1.1.1.1\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_one_below_maximum_ip_and_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1072, in test_calculate_range_in_ip_format_with_one_below_maximum_ip_and_maximum_subnet\n    self.assertEquals('254.254.240.0', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '254.254.240.0' != '254.254.254.254'\n- 254.254.240.0\n?           - ^\n+ 254.254.254.254\n?          +  ^^^\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_well_above_minimum_ip_and_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1047, in test_calculate_range_in_ip_format_with_well_above_minimum_ip_and_minimum_subnet\n    self.assertEquals('255.255.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '255.255.255.254' != '160.160.160.160'\n- 255.255.255.254\n+ 160.160.160.160\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_well_above_minimum_ip_and_well_above_minimum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1052, in test_calculate_range_in_ip_format_with_well_above_minimum_ip_and_well_above_minimum_subnet\n    self.assertEquals('160.167.255.254', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '160.167.255.254' != '160.160.160.160'\n- 160.167.255.254\n+ 160.160.160.160\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_well_below_maximum_ip_and_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1077, in test_calculate_range_in_ip_format_with_well_below_maximum_ip_and_maximum_subnet\n    self.assertEquals('none', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: 'none' != '160.160.160.160'\n- none\n+ 160.160.160.160\n\n"
    },
    {
      "test": "subnet_calculator_tests.TestCalculateIpv4UpperRange.test_calculate_range_in_ip_format_with_well_below_maximum_ip_and_well_below_maximum_subnet",
      "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py\", line 1087, in test_calculate_range_in_ip_format_with_well_below_maximum_ip_and_well_below_maximum_subnet\n    self.assertEquals('160.160.160.0', subnet)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1321, in deprecated_func\n    return original_func(*args, **kwargs)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '160.160.160.0' != '160.160.160.160'\n- 160.160.160.0\n+ 160.160.160.160\n?             ++\n\n"
    }
  ],
  "tests-run": 222
}